Rabah/urls.py
from decouple import config
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from users.views import RabahSignupView, RabahLoginView

admin_url = config("ADMIN_URL", default="admin_dont_url")

urlpatterns = [
    path(f"{admin_url}/", admin.site.urls, name="admin"),
    path("users/", include("users.urls"), name="users"),
    path("", include("rabah_dashboard.urls"), name="rabah_dashboard"),
    path(
        "organisations/",
        include("rabah_organisations.urls"),
        name="rabah_organisations",
    ),
    path("member/", include("rabah_members.urls"), name="rabah_members"),
    path(
        "rabah_contributions/",
        include("rabah_contributions.urls"),
        name="rabah_contributions",
    ),
    path("event/", include("rabah_events.urls"), name="rabah_events"),
    path(
        "subscription/", include("rabah_subscriptions.urls"), name="rabah_subscriptions"
    ),
    path("accounts/login/", RabahLoginView.as_view(), name="account_login"),
    path("accounts/signup/", RabahSignupView.as_view(), name="account_signup"),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rabah_dashboard/urls.py
from django.urls import path

from .views import (
    DashBoardView,
    UserOrganisationsView,
    RabahHomePageView,
    RabahContactUsPageView,
    RabahAboutUsPageView, RabahServicesPageView, RabahContactSupportPageView,
)

app_name = "rabah_dashboard"
urlpatterns = [
    path("", RabahHomePageView.as_view(), name="home_page"),
    path("contact_us/", RabahContactUsPageView.as_view(), name="contact_us"),
    path("contact_support/", RabahContactSupportPageView.as_view(), name="contact_support"),
    path("about_us/", RabahAboutUsPageView.as_view(), name="about_us"),
    path("services/", RabahServicesPageView.as_view(), name="services"),
    path("dashbaord/", DashBoardView.as_view(), name="dashboard"),
    path(
        "user_organisations/",
        UserOrganisationsView.as_view(),
        name="user_organisations",
    ),
]

templates/new_page/contactsupport.html
{% extends "new_page/base.html" %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static "new_page/css/contact.css" %}">
{% endblock %}

{% block title %}

{% endblock %}

{% block content %}
    <div class="cs-conatainer">
        <div class="cs-div">
            <h1>Contact Support</h1>
            <form class="form" action="{% url 'rabah_dashboard:contact_us' %}" method="post" >
                {% csrf_token %}
                <div class="form-container">
                    <label for="name">Name</label>
                    <input type="text" name="name" placeholder="Full Name" id="">
                </div>
                <div class="form-container">
                    <label for="email">Email</label>
                    <input type="text" name="email" placeholder="Enter your mail" id="">
                </div>
                <div class="form-container">
                    <label for="mobile">Mobile (Optional)</label>
                    <input type="text" name="mobile" placeholder="0813XXXXXXX04" id="">
                </div>
                <div class="form-container">
                    <label for="msg">Message</label>
                    <textarea name="message" placeholder="How can we help you?" id=""></textarea>
                    <br>

                    <!-- <img src="./images/captcha.png" alt="captcha" id="captcha">
                    <input type="text" name="captcha" placeholder="Enter the captcha" id="captcha-input">
                    br -->
                    <button id="submit-btn">Send Message</button>
                </div>
            </form>

        </div>
    </div>
{% endblock %}

templates/new_page/service.html
{% extends "new_page/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "new_page/css/services.css" %}">
{% endblock %}

{% block title %}
Rabah360|Services
{% endblock %}


{% block content %}
    <div class="first-service-container">
        <div class="our-service-label">
            Our Services
        </div>
        <h1 class="whyrabah">Why Rabah360?</h1>
        <div class="servicefirtground">
            <div class="service-div">
                <div class="service-img-div">
                    <img src="{% static 'new_page/images/cross.png' %}" alt="">
                </div>
                <h1>Church Management Software</h1>
                <p>Tailored for churches, Rabah Event Management is designed to support you in capturing and managing your church data effectively. Its user-friendly capability, coupled with customized features ensures you have an overview of each aspect of your church at any point in time, from wherever you are.
                </p>
            </div>
            <div class="service-div">
                <div class="service-img-div">
                    <img src="{% static 'new_page/images/dinnar.png' %}" alt="">
                </div>
                <h1>People Management</h1>
                <p>Rabah360 takes member data management to the next level with a customizable approach that perfectly fits your church's unique needs. Easily store and access relevant information while enjoying the flexibility to tailor the system to match your specific requirements. Empower your ministry with Rabah360's tailored member management solution and streamline your administrative tasks with precision and ease.</p>
            </div>
            <div class="service-div">
                <div class="service-img-div">
                    <img src="{% static 'new_page/images/chart.png' %}" alt="">
                </div>
                <h1>Attendance Precision: Know Your  Participation</h1>
                <p>With Rabah360's Attendance Tracking feature, gain valuable insights into your church's engagement levels at every event, be it a regular service or a special program. Effortlessly monitor and analyze attendance figures to understand participation trends and ensure every member feels connected and valued in your church community. Stay informed, stay engaged, with Rabah360.</p>
            </div>
            <div class="service-div">
                <div class="service-img-div">
                    <img src="{% static 'new_page/images/effort.png' %}" alt="">
                </div>
                <h1>Effortless Check-ins: Simplify Service Participation</h1>
                <p>Rabah360's Check-in feature revolutionizes event management by enabling seamless check-ins for both children and adults at the click of a button. Ensure smooth transitions and enhanced  safety protocols while maximizing participation in your services and events. Simplify your check-in process with Rabah360 and focus on creating meaningful experiences for your congregation.</p>
            </div>
            <div class="service-div">
                <div class="service-img-div">
                    <img src="{% static 'new_page/images/book.png' %}" alt="">
                </div>
                <h1>Streamlined Event Management: Plan with Precision</h1>
                <p>Rabah360 empowers your church to organize events and services effortlessly with our Manage Events and Services feature. Calendarize your entire year's schedule, keeping your members informed and engaged. Ensure everyone knows what to expect and can plan accordingly, fostering a vibrant and connected church community. Plan with precision and elevate your events with Rabah360. </p>
            </div>
            <div class="service-div">
                <div class="service-img-div">
                    <img src="{% static 'new_page/images/fellowship.png' %}" alt="">
                </div>
                <h1>Fellowship Groups: Strengthen Community Bonds</h1>
                <p>Rabah360's Groups feature empowers your church to cultivate strong fellowship connections. Customize specific groups tailored to your church's needs, enabling targeted communication and personalized engagement. Track and monitor each member's participation within their respective groups to ensure meaningful engagement and foster a sense of belonging within your community. Strengthen your church's bonds and nurture a vibrant, connected fellowship with Rabah360. </p>
            </div>
            <div class="service-div">
                <div class="service-img-div">
                    <img src="{% static 'new_page/images/financial.png' %}" alt="">
                </div>
                <h1>Financial Stewardship Transparency and Insight</h1>
                <p>Rabah360's Giving &amp; Finances feature is your key to transparent and efficient financial management. Record and track member giving promptly, ensuring accurate and up-to-date financial records. Gain a comprehensive view of your church's financial health at any time and review progress towards your financial goals. With Rabah360, empower your church with the tools needed for responsible financial stewardship and strategic planning.</p>
            </div>
            <div class="service-div">
                <div class="service-img-div">
                    <img src="{% static 'new_page/images/work.png' %}" alt="">
                </div>
                <h1>Efficient Collaboration: Seamless Church Administration</h1>
                <p>Rabah360's Giving &amp; Finances feature is your key to transparent and efficient financial management. Record and track member giving promptly, ensuring accurate and up-to-date financial records. Gain a comprehensive view of your church's financial health at any time and review progress towards your financial goals. With Rabah360, empower your church with the tools needed for responsible financial stewardship and strategic planning.</p>
            </div>
            <div class="service-div">
                <div class="service-img-div">
                    <img src="{% static 'new_page/images/data.png' %}" alt="">
                </div>
                <h1>Data-Driven Insights</h1>
                <p>Rabah360's Analytics feature illuminates the path to a more informed and impactful ministry. Our comprehensive dashboard provides key figures and insights across various aspects of your database, empowering you to make data-driven decisions with confidence. Gain valuable insights into attendance trends, giving patterns, engagement levels, and more, all in one centralized location. With Rabah360's Analytics, unlock the power of data to enhance your ministry's effectiveness and nurture meaningful connections within your church community.</p>
            </div>
            <div >
                <!-- <div class="service-img-div">
                    <img src="{% static 'new_page/images/data.png' %}" alt="">
                </div>
                <h1>Data-Driven Insights</h1>
                <p>Rabah360's Analytics feature illuminates the path to a more informed and impactful ministry. Our comprehensive dashboard provides key figures and insights across various aspects of your database, empowering you to make data-driven decisions with confidence. Gain valuable insights into attendance trends, giving patterns, engagement levels, and more, all in one centralized location. With Rabah360's Analytics, unlock the power of data to enhance your ministry's effectiveness and nurture meaningful connections within your church community.</p> -->
            </div>
        </div>
    </div>
    <div class="faq">
        <div class="faq-label">
            Faq’s
        </div>
        <div class="d">
            <!-- FAQ 1 -->
            <div class="faq-details" onclick="toggleDetails(this)">
                <div>
                    <p class="me">What is Rabah360?</p>
                    <!-- The content is inside the same div -->
                    <div class="details-content" style="display: none;">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae placeat veniam id beatae corporis quos. Aperiam molestiae laudantium, atque exercitationem similique deleniti consectetur quaerat mollitia perferendis deserunt ipsam, eius enim.</p>
                    </div>
                </div>
                <svg width="33" height="32" viewBox="0 0 33 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g id="Slider">
                        <path id="Vector" d="M22.1258 12.3906L16.4018 18.1146L10.6778 12.3906L8.79248 14.276L16.4018 21.8853L24.0111 14.276L22.1258 12.3906Z" fill="black" />
                    </g>
                </svg>

                <!-- The content is inside the same div -->
                <div class="details-content" style="display: none;">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae placeat veniam id beatae corporis quos. Aperiam molestiae laudantium, atque exercitationem similique deleniti consectetur quaerat mollitia perferendis deserunt ipsam, eius enim.</p>
                </div>
            </div>

            <!-- FAQ 2 -->
            <div class="faq-details-sec" onclick="toggleDetails(this)">
                <div>
                    <p class="me">Who is it meant for?</p>
                    <!-- The content is inside the same div -->
                    <div class="details-content" style="display: none;">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae placeat veniam id beatae corporis quos. Aperiam molestiae laudantium, atque exercitationem similique deleniti consectetur quaerat mollitia perferendis deserunt ipsam, eius enim.</p>
                    </div>
                </div>
                <svg width="33" height="32" viewBox="0 0 33 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g id="Slider">
                        <path id="Vector" d="M22.1258 12.3906L16.4018 18.1146L10.6778 12.3906L8.79248 14.276L16.4018 21.8853L24.0111 14.276L22.1258 12.3906Z" fill="black" />
                    </g>
                </svg>


            </div>

            <!-- FAQ 3 -->
            <div class="faq-details-sec" onclick="toggleDetails(this)">
                <div>
                    <p class="me">Is your platform moderated? If yes, why?</p>
                    <!-- The content is inside the same div -->
                    <div class="details-content" style="display: none;">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae placeat veniam id beatae corporis quos. Aperiam molestiae laudantium, atque exercitationem similique deleniti consectetur quaerat mollitia perferendis deserunt ipsam, eius enim.</p>
                    </div>
                </div>
                <svg width="33" height="32" viewBox="0 0 33 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g id="Slider">
                        <path id="Vector" d="M22.1258 12.3906L16.4018 18.1146L10.6778 12.3906L8.79248 14.276L16.4018 21.8853L24.0111 14.276L22.1258 12.3906Z" fill="black" />
                    </g>
                </svg>
            </div>

            <!-- FAQ 4 -->
            <div class="faq-details-third" onclick="toggleDetails(this)">

                <div>
                    <p class="me">Can I become a merchant within the platform?</p>
                    <!-- The content is inside the same div -->
                    <div class="details-content" style="display: none;">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae placeat veniam id beatae corporis quos. Aperiam molestiae laudantium, atque exercitationem similique deleniti consectetur quaerat mollitia perferendis deserunt ipsam, eius enim.</p>
                    </div>
                </div>
                <svg width="33" height="32" viewBox="0 0 33 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g id="Slider">
                        <path id="Vector" d="M22.1258 12.3906L16.4018 18.1146L10.6778 12.3906L8.79248 14.276L16.4018 21.8853L24.0111 14.276L22.1258 12.3906Z" fill="black" />
                    </g>
                </svg>
            </div>


        </div>
    </div>
{% endblock %}