Rabah/urls.py
from decouple import config
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from users.views import RabahSignupView, RabahLoginView

admin_url = config("ADMIN_URL", default="admin_dont_url")

urlpatterns = [
    path(f"{admin_url}/", admin.site.urls, name="admin"),
    path("users/", include("users.urls"), name="users"),
    path("", include("rabah_dashboard.urls"), name="rabah_dashboard"),
    path(
        "organisations/",
        include("rabah_organisations.urls"),
        name="rabah_organisations",
    ),
    path("member/", include("rabah_members.urls"), name="rabah_members"),
    path(
        "rabah_contributions/",
        include("rabah_contributions.urls"),
        name="rabah_contributions",
    ),
    path("event/", include("rabah_events.urls"), name="rabah_events"),
    path(
        "subscription/", include("rabah_subscriptions.urls"), name="rabah_subscriptions"
    ),
    path("accounts/login/", RabahLoginView.as_view(), name="account_login"),
    path("accounts/signup/", RabahSignupView.as_view(), name="account_signup"),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rabah_contributions/urls.py
from django.urls import path

from .views import (
    GivingContributionView,
    ContributionTypeView,
    ContributionTypeUpdateView,
    ContributionTypeDeleteView,
    ContributionsView,
    ContributionDeleteView,
    ContributionUpdateView,
)

app_name = "rabah_contributions"
urlpatterns = [
    path(
        "add_contribution_type",
        ContributionTypeView.as_view(),
        name="add_contribution_type",
    ),
    path(
        "update_contribution_type/<str:contribution_type_id>/",
        ContributionTypeUpdateView.as_view(),
        name="update_contribution_type",
    ),
    path(
        "delete_contribution_type/<str:contribution_type_id>/",
        ContributionTypeDeleteView.as_view(),
        name="delete_contribution_type",
    ),
    path(
        "contributions/<str:contribution_type_id>/",
        ContributionsView.as_view(),
        name="contributions",
    ),
    path(
        "contribution_delete/<str:contribution_id>/",
        ContributionDeleteView.as_view(),
        name="contribution_delete",
    ),
    path(
        "add_giving_transaction",
        GivingContributionView.as_view(),
        name="add_giving_transaction",
    ),
    path(
        "contribution_update/<str:contribution_id>",
        ContributionUpdateView.as_view(),
        name="contribution_update",
    ),
]

rabah_dashboard/urls.py
from django.urls import path

from .views import (
    DashBoardView,
    UserOrganisationsView,
    RabahHomePageView,
    RabahContactUsPageView,
    RabahAboutUsPageView, RabahServicesPageView, RabahContactSupportPageView,
)

app_name = "rabah_dashboard"
urlpatterns = [
    path("", RabahHomePageView.as_view(), name="home_page"),
    path("contact_us/", RabahContactUsPageView.as_view(), name="contact_us"),
    path("contact_support/", RabahContactSupportPageView.as_view(), name="contact_support"),
    path("about_us/", RabahAboutUsPageView.as_view(), name="about_us"),
    path("services/", RabahServicesPageView.as_view(), name="services"),
    path("dashbaord/", DashBoardView.as_view(), name="dashboard"),
    path(
        "user_organisations/",
        UserOrganisationsView.as_view(),
        name="user_organisations",
    ),
]

rabah_members/urls.py
from django.urls import path

from .views import (
    MembersDashboardView,
    GroupMembersView,
    MemberDetailView,
    MemberCreateView,
    AddFamilyMemberView,
    MemberAutocompleteView,
    AddExistingMemberToFamilyView,
    UpdateExistingMemberFamilyRelationShipView,
    MemberUploadCreateView,
    MemberAddLoginPermissionView, MemberInvitationCreateView, MemberAcceptInvitationView,
)

app_name = "rabah_members"
urlpatterns = [
    path("autocomplete/", MemberAutocompleteView.as_view(), name="member_autocomplete"),
    path("members/", MembersDashboardView.as_view(), name="members"),
    path("add_member/", MemberCreateView.as_view(), name="add_member"),
    path(
        "add_member_file_upload/",
        MemberUploadCreateView.as_view(),
        name="add_member_file_upload",
    ),
    # member update
    path(
        "member_login_premission/<str:member_id>/",
        MemberAddLoginPermissionView.as_view(),
        name="member_login_permission",
    ),
    path(
        "add_member/<str:member_id>/",
        AddFamilyMemberView.as_view(),
        name="add_family_member",
    ),
    path(
        "add_existing_member_to_family/<str:member_id>/",
        AddExistingMemberToFamilyView.as_view(),
        name="add_existing_member_to_family",
    ),
    path(
        "update_existing_member_to_family/",
        UpdateExistingMemberFamilyRelationShipView.as_view(),
        name="update_existing_member_to_family",
    ),
    # member for gorups routes
    path("members/<str:group_id>/", GroupMembersView.as_view(), name="group_members"),
    path(
        "member_detail/<str:id>/",
        MemberDetailView.as_view(),
        name="group_member_detail",
    ),

    path("member-invitation-create/", MemberInvitationCreateView.as_view(), name="member-invitation-create"),
    path("member-accept-invitation/<str:member_invitation_id>/", MemberAcceptInvitationView.as_view(), name="member-accept-invitation"),
]

users/urls.py
from django.urls import path


from .views import UserProfileView, ChangeUserPassword, CustomLogout, MemberUserProfileUpdateView, \
    MemberCreatePasswordView, SetTimeZone


app_name = "user"
urlpatterns = [
    path("user_profile/", UserProfileView.as_view(), name="user_profile"),
    path("member_profile_edit/<str:profile_id>/", MemberUserProfileUpdateView.as_view(), name="member_profile_edit"),
    path("change_user_password/", ChangeUserPassword.as_view(), name="change_user_password"),

    # change user password when login
    path("member_create_password/<str:token>/", MemberCreatePasswordView.as_view(), name="member_create_password"),

    # member invited to an organisation and need to create a password
    path("custom_logout", CustomLogout.as_view(), name="custom_logout"),
    path("set_timezone", SetTimeZone.as_view(), name="set_timezone"),

]

templates/dashboard/add_member.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_filters %}


{% block css %}

{% endblock %}

{% block title %}
Add Memeber | Rabah
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-main">
                    <h4 class="text-capitalize breadcrumb-title">Member</h4>
                    <div class="breadcrumb-action justify-content-center flex-wrap">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url "rabah_dashboard:dashboard" %}"><i
                                        class="uil uil-estate"></i>Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Add Member</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mx-auto">
                <div class="d-flex justify-content-center" style="min-width: 100%">
                    <div class="card card-default card-md mb-4" style="min-width: 100%">
                        <div class="card-header">
                            <h6>Member Create</h6>
                        </div>
                        <div class="card-body">
                            <div class="basic-form-">
                                <form action="{% url "rabah_members:add_member" %}" method="post">
                                {% csrf_token %}
                                    {{ form|crispy }}
                                    {% if form.errors %}
                                        <div class="alert alert-danger">
                                            <strong>Error:</strong>
                                            <ul>
                                                {% for field, error_list in form.errors.items %}
                                                    {% for error in error_list %}
                                                        <li>{{ field|capfirst }}: {{ error }}</li>
                                                    {% endfor %}
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    {% endif %}
                                    <div class="form-group mb-0">
                                        <button type="submit" class="btn btn-lg btn-primary btn-submit">Add Member
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}


{% block script %}

{% endblock %}

templates/dashboard/contribution_type.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_filters %}


{% block css %}

{% endblock %}

{% block title %}
    Contribution Type | Rabah
{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-main">
                    <h4 class="text-capitalize breadcrumb-title">Contribution Type</h4>
                    <div class="breadcrumb-action justify-content-center flex-wrap">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url "rabah_dashboard:dashboard" %}"><i
                                        class="uil uil-estate"></i>Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Donation</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-12">

                <div class="userDatatable global-shadow border-light-0 p-30 bg-white radius-xl w-100 mb-30">
                    <div class="table-responsive">
                        <table class="table mb-0 table-borderless">
                            <thead>
                            <tr class="userDatatable-header">
                                <th>
                                    <span class="userDatatable-title">Name</span>
                                </th>
                                <th>
                                    <span class="userDatatable-title">Date Created</span>
                                </th>
                                <th>
                                    <span class="userDatatable-title">Amount Contributed</span>
                                </th>


                                <th>
                                    <span class="userDatatable-title float-end">action</span>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for contribution_type in contribution_types %}

                                <tr>
                                    <td>
                                        <div class="userDatatable-content">
                                            <a href="{% url "rabah_contributions:contributions" contribution_type.id %}">{{ contribution_type.name }}</a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="userDatatable-content">
                                            {{ contribution_type.timestamp }}
                                        </div>
                                    </td>
                                    <td>
                                        <div class="userDatatable-content">
                                            {{ contribution_type.get_amount_contributed }}
                                        </div>
                                    </td>

                                    <td>
                                        <ul class="orderDatatable_actions mb-0 d-flex flex-wrap" style="justify-content: flex-end !important;">

                                            <li>
                                                <a href="#" class="edit" data-bs-toggle="modal"
                                                   data-bs-target="#contribution_type_{{ contribution_type.id }}">
                                                    <i class="uil uil-edit"></i>
                                                </a>


                                                <div class="modal fade new-member "
                                                     id="contribution_type_{{ contribution_type.id }}" role="dialog"
                                                     tabindex="-1"
                                                     aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                                    <div class="modal-dialog modal-dialog-centered">
                                                        <div class="modal-content  radius-xl">
                                                            <div class="modal-header">
                                                                <h6 class="modal-title fw-500" id="staticBackdropLabel">
                                                                    Update Contribution Type</h6>
                                                                <button type="button" class="close"
                                                                        data-bs-dismiss="modal" aria-label="Close">
                                                                    <i class="uil uil-multiply"></i>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <div class="new-member-modal">
                                                                    <form method="post"
                                                                          action="{% url "rabah_contributions:update_contribution_type" contribution_type.id %}"
                                                                          enctype="multipart/form-data">
                                                                        {% csrf_token %}
                                                                        <div id="div_id_name" class="form-group"><label
                                                                                for="id_name" class=" requiredField">
                                                                            Name<span class="asteriskField">*</span>
                                                                        </label>
                                                                            <div><input type="text" name="name"
                                                                                        maxlength="250"
                                                                                        value="{{ contribution_type.name }}"
                                                                                        class="textinput textInput form-control"
                                                                                        required="" id="id_name"></div>
                                                                        </div>
                                                                        <div class="button-group d-flex pt-25">
                                                                            <button class="btn btn-primary btn-default btn-squared text-capitalize"
                                                                                    type="submit">
                                                                                update
                                                                            </button>
                                                                            <button type="button"
                                                                                    class="btn btn-light btn-default btn-squared fw-400 text-capitalize b-light color-light"
                                                                                    data-bs-dismiss="modal">cancel
                                                                            </button>
                                                                        </div>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                            <li>
                                                <a href="{% url "rabah_contributions:delete_contribution_type" contribution_type.id %}"
                                                   class="remove">
                                                    <i class="uil uil-trash-alt"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <div class="d-flex justify-content-end pt-30">
                        <nav class="dm-page">
                            <ul class="dm-pagination d-flex">
                                {% if contribution_types.has_previous %}
                                    <li class="dm-pagination__item">
                                        <a href="?page=1" class="dm-pagination__link pagination-control">
                                            <span class="la la-angle-left"></span>
                                        </a>
                                    </li>
                                {% endif %}

                                {% for page in contribution_types.paginator.page_range %}
                                    <li class="dm-pagination__item ">
                                        <a href="?page={{ page }}"
                                           class="dm-pagination__link {% if contribution_types.number == page %}active{% endif %}">
                                            <span class="page-number">{{ page }}</span>
                                        </a>
                                    </li>
                                {% endfor %}

                                {% if contribution_types.has_next %}
                                    <li class="dm-pagination__item">
                                        <a href="?page={{ contribution_types.paginator.num_pages }}"
                                           class="dm-pagination__link pagination-control">
                                            <span class="la la-angle-right"></span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>

                </div>


            </div>
            <div class="col-lg-6">
                <div class="card card-default  mb-4">
                    <div class="card-header">
                        <h6>Add Donation</h6>
                    </div>
                    <div class="card-body mx-md-5">
                        <form action="{% url "rabah_contributions:add_contribution_type" %}" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}

                            <button type="submit" class="btn btn-primary float-end">Add Contribution Type</button>
                        </form>

                    </div>
                </div>

            </div>


        </div>
    </div>
{% endblock %}


{% block script %}

{% endblock %}

templates/dashboard/giving_transaction.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_filters %}


{% block css %}
    <style>
        /* Styles for the selected members list */
        #selected-members-list {
            list-style: none;
            padding: 0;
            margin: 10px 0;
        }

        .selected-member-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            margin-bottom: 5px;
        }


        #member-suggestions li {
            cursor: pointer;
            border: 1px solid #ccc;
            border-radius: 4px;
            margin: 10px 10px 5px;
        }

        #member-suggestions li img {
            /* Your styles for the images go here */
            max-width: 60px; /* Adjust the max-width as needed */
            border-radius: 50%; /* Add a border-radius for rounded images, adjust as needed */
            margin-right: 10px; /* Add margin for spacing between the image and the text */
        }

        .selected-member-item img {
            width: 30px; /* Adjust the width to your preference */
            height: 30px; /* Adjust the height to your preference */
            border-radius: 50%;
            margin-right: 10px;
        }

        .selected-member-item span {
            flex-grow: 1;
            margin-right: 10px;
        }

        .cancel-button {
            background-color: #dc3545;
            color: #fff;
            border: none;
            padding: 5px 10px;
            cursor: pointer;
            border-radius: 4px;
        }

        .cancel-button:hover {
            background-color: #c82333;
        }

    </style>
{% endblock %}


{% block title %}
    Giving | Rabah
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-main">
                    <h4 class="text-capitalize breadcrumb-title">Donation</h4>
                    <div class="breadcrumb-action justify-content-center flex-wrap">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url "rabah_dashboard:dashboard" %}"><i
                                        class="uil uil-estate"></i>Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Donation</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card card-default  mb-4">
                    <div class="card-header">
                        <h6>Add Donation</h6>
                    </div>
                    <div class="card-body mx-md-5">
                        <form action="{% url "rabah_contributions:add_giving_transaction" %}" method="post">
                            {% csrf_token %}
                            {{ form.contribution_type|as_crispy_field }}
                            {{ form.member_id|as_crispy_field }}
                            {{ form.member_name|as_crispy_field }}
                            <ul id="member-suggestions"></ul>
                            <div id="selected-members-container">
                                <ul id="selected-members-list"></ul>
                            </div>
                            {{ form.method|as_crispy_field }}
                            {{ form.amount|as_crispy_field }}
                            {{ form.description|as_crispy_field }}
                            {{ form.is_anonymous|as_crispy_field }}
                            <button type="submit" class="btn btn-primary float-end">Add Giving Transaction</button>
                            {% if contribution %}
                                <a href="{% url "rabah_contributions:contributions" contribution.id %}" class="btn btn-primary"> View All </a>
                            {% endif %}
                        </form>

                    </div>
                </div>

            </div>

        </div>
    </div>
{% endblock %}



{% block script %}
    {% comment %} For Adding Existing members{% endcomment %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var memberInput = document.getElementById('id_member_name');
            var memberInputID = document.getElementById('id_member_id');
            var suggestionsList = document.getElementById('member-suggestions');

            memberInput.addEventListener('input', function () {
                var query = memberInput.value;

                // Make an AJAX request to your backend endpoint using fetch
                fetch('/member/autocomplete/?query=' + encodeURIComponent(query))
                    .then(response => response.json())
                    .then(data => {
                        // Update suggestions based on backend response
                        updateMemberSuggestions(data);
                    })
                    .catch(error => {
                        console.error('Error fetching member suggestions:', error);
                    });
            });

            suggestionsList.addEventListener('click', function (event) {
                console.log("clicked ")
                console.log("clicked ", event.target.tagName)
                if (event.target.tagName === 'LI') {
                    // Use the data directly from the suggestion list
                    var selectedMemberId = event.target.dataset.uuid;
                    var selectedMemberDetails = {
                        id: selectedMemberId,
                        name: event.target.querySelector('span').textContent,
                        image_url: event.target.querySelector('img').src, // Replace with the actual property name
                        additional_info: '' // Replace with the actual property name or remove if not needed
                    };


                    // Clear the input and suggestions
                    memberInput.value = selectedMemberDetails.name;
                    memberInputID.value = selectedMemberDetails.id;
                    suggestionsList.innerHTML = '';
                }
            });


            function updateMemberSuggestions(suggestions) {
                suggestionsList.innerHTML = '';

                if (suggestions.length > 0) {
                    suggestions.forEach(function (member) {
                        var listItem = document.createElement('li');

                        // Create an image element
                        var memberImage = document.createElement('img');
                        memberImage.src = member.image_url; // Replace with actual image URL
                        memberImage.alt = member.name; // Replace with alt text
                        listItem.appendChild(memberImage);

                        // Create a span element for the member's name
                        var memberName = document.createElement('span');
                        memberName.textContent = member.name; // Adjust the property based on your data
                        listItem.appendChild(memberName);

                        // Set the dataset for the member's UUID
                        listItem.dataset.uuid = member.id; // Assuming your member object has an 'id' property

                        // Append the list item to the suggestions list
                        suggestionsList.appendChild(listItem);
                    });
                } else {
                    var noMatchItem = document.createElement('li');
                    noMatchItem.textContent = 'No matching members found.';
                    suggestionsList.appendChild(noMatchItem);
                }
            }
        });

    </script>
    {% comment %} IS anonymout{% endcomment %}
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            // Function to toggle member name based on is_anonymous checkbox
            function toggleMemberName() {
                var isAnonymousChecked = document.getElementById("id_is_anonymous").checked;
                var memberNameDiv = document.getElementById("div_id_member_name");

                if (isAnonymousChecked) {
                    memberNameDiv.style.display = "none";
                } else {
                    memberNameDiv.style.display = "block";
                }
            }

            // Initial toggle based on a page load
            toggleMemberName();

            // Attach an event listener to the is_anonymous checkbox
            document.getElementById("id_is_anonymous").addEventListener("change", function () {
                toggleMemberName();
            });
        });
    </script>

{% endblock %}